name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-objective-git:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ macOS-12 ]
        xcode: [ Xcode_14.2, Xcode_13.4 ]
    steps:
      - name: ls Xcode
        run: ls -la /Applications/Xcode*
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Show openssl version
        run: |
          openssl version
      - name: pre build
        run: script/bootstrap && script/update_libgit2
      - name: Show openssl version
        run: |
          openssl version
      - name: Test and archive project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test archive ARCHS="x86_64"
