name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-objective-git:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ macOS-13 ]
        xcode: [ 14.1, 14.2, 15.1, 15.2 ]
        arch: [ x86_64 ]
    steps:
      - name: ls Xcode
        run: ls -la /Applications/Xcode*
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Show openssl version
        run: |
          openssl version
      - run: script/bootstrap
      - run: script/update_libgit2
      - name: Show openssl version
        run: |
          openssl version
      - name: Test project ${{ matrix.arch }}
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test ARCHS="${{ matrix.arch }}"
      - name: Archive project ${{ matrix.arch }}
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive ARCHS="${{ matrix.arch }}"
